import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.marketplace': 'Marketplace',
    'nav.blog': 'Blog',
    'nav.about': 'About',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.weather': 'Weather',
    'nav.aichat': 'AI Chat',
    'nav.calendar': 'Crop Calendar',
    'nav.notifications': 'Notifications',
    'nav.cart': 'Cart',
    'nav.chat': 'Chat',
    
    // Homepage
    'home.title': 'Connect Directly with Sri Lankan Farmers',
    'home.subtitle': 'Fresh produce, fair prices, AI-powered insights',
    'home.cta.farmer': 'I am a Farmer',
    'home.cta.buyer': 'I am a Buyer',
    'home.ai.title': 'AI-Powered Agriculture',
    'home.ai.description': 'Get smart recommendations for crops, prices, and farming techniques',
    
    // Marketplace
    'marketplace.title': 'Fresh Produce Marketplace',
    'marketplace.search': 'Search products...',
    'marketplace.filter.all': 'All Categories',
    'marketplace.filter.vegetables': 'Vegetables',
    'marketplace.filter.fruits': 'Fruits',
    'marketplace.filter.grains': 'Grains',
    'marketplace.addtocart': 'Add to Cart',
    'marketplace.viewproduct': 'View Product',
    
    // Admin
    'admin.communications': 'Communications',
    'admin.sendemail': 'Send Email',
    'admin.sendsms': 'Send SMS',
    'admin.phonenumbers': 'Phone Numbers',
    'admin.recipient': 'Recipient',
    'admin.subject': 'Subject',
    'admin.message': 'Message',
    'admin.customEmail': 'Custom Email',
    'admin.customPhone': 'Custom Phone Number',
    'admin.allusers': 'All Users',
    'admin.allfarmers': 'All Farmers',
    'admin.allbuyers': 'All Buyers',
    'admin.selectrecipient': 'Select recipient type',
    'admin.sendingemail': 'Sending Email...',
    'admin.sendingsms': 'Sending SMS...',
    'admin.emailsent': 'Email Sent Successfully',
    'admin.smssent': 'SMS Sent Successfully',
    'admin.emailfailed': 'Failed to send email. Please try again.',
    'admin.smsfailed': 'Failed to send SMS. Please check the phone number and try again.',
    'admin.fillfields': 'Please fill in all fields',
    'admin.enterphone': 'Please enter a phone number',
    'admin.enteremail': 'Enter email address',
    'admin.entersubject': 'Enter email subject',
    'admin.entermessage': 'Enter your message',
    'admin.enterphonenumber': 'Enter phone number',
    'admin.maxchars': 'characters',
    'admin.refreshphone': 'Refresh Phone Numbers',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.contact': 'Contact',
    'common.name': 'Name',
    'common.usertype': 'User Type',
    'common.location': 'Location',
    'common.verified': 'Verified',
    'common.unverified': 'Unverified',
    'common.notspecified': 'Not specified',
    'common.nophone': 'No phone numbers found',
    'common.loadingphone': 'Loading phone numbers...',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.actions': 'Actions',
    
    // Authentication
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.farmer': 'Farmer',
    'auth.buyer': 'Buyer',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.location': 'Location',
    'auth.logout': 'Logout',
    'auth.profile': 'Profile',
    'auth.settings': 'Settings',
    
    // Buttons and actions
    'btn.send': 'Send',
    'btn.edit': 'Edit',
    'btn.delete': 'Delete',
    'btn.view': 'View',
    'btn.update': 'Update',
    'btn.create': 'Create',
    'btn.add': 'Add',
    'btn.remove': 'Remove',
    'btn.close': 'Close',
    'btn.open': 'Open',
    'btn.refresh': 'Refresh',
    'btn.reset': 'Reset',
    'btn.confirm': 'Confirm',
  },
  si: {
    // Navigation
    'nav.home': 'මුල් පිටුව',
    'nav.marketplace': 'වෙළඳපල',
    'nav.blog': 'බ්ලොග්',
    'nav.about': 'අපි ගැන',
    'nav.login': 'ප්‍රවේශය',
    'nav.register': 'ලියාපදිංචිය',
    'nav.dashboard': 'උපකරණ පුවරුව',
    'nav.admin': 'පරිපාලක',
    'nav.weather': 'කාලගුණය',
    'nav.aichat': 'AI කතාබස්',
    'nav.calendar': 'බෝග දිනදර්ශනය',
    'nav.notifications': 'දැනුම්දීම්',
    'nav.cart': 'කරත්තය',
    'nav.chat': 'කතාබස්',
    
    // Homepage
    'home.title': 'ශ්‍රී ලංකාවේ ගොවීන් සමඟ සෘජුවම සම්බන්ධ වන්න',
    'home.subtitle': 'නැවුම් නිෂ්පාදන, සාධාරණ මිල, AI බුද්ධිමත් අවබෝධය',
    'home.cta.farmer': 'මම ගොවියෙක්',
    'home.cta.buyer': 'මම ගැනුම්කරුවෙක්',
    'home.ai.title': 'AI බලගන්වන කෘෂිකර්මාන්තය',
    'home.ai.description': 'බෝග, මිල සහ ගොවිතාන් ක්‍රම සඳහා බුද්ධිමත් නිර්දේශ ලබා ගන්න',
    
    // Marketplace
    'marketplace.title': 'නැවුම් නිෂ්පාදන වෙළඳපල',
    'marketplace.search': 'නිෂ්පාදන සොයන්න...',
    'marketplace.filter.all': 'සියලු කාණ්ඩ',
    'marketplace.filter.vegetables': 'එළවළු',
    'marketplace.filter.fruits': 'පලතුරු',
    'marketplace.filter.grains': 'ධාන්‍ය',
    'marketplace.addtocart': 'කරත්තයට එක් කරන්න',
    'marketplace.viewproduct': 'නිෂ්පාදනය බලන්න',
    
    // Admin
    'admin.communications': 'සන්නිවේදනය',
    'admin.sendemail': 'ඊමේල් යවන්න',
    'admin.sendsms': 'SMS යවන්න',
    'admin.phonenumbers': 'දුරකථන අංක',
    'admin.recipient': 'ලබන්නා',
    'admin.subject': 'විෂය',
    'admin.message': 'පණිවිඩය',
    'admin.customEmail': 'අභිරුචි ඊමේල්',
    'admin.customPhone': 'අභිරුචි දුරකථන අංකය',
    'admin.allusers': 'සියලු පරිශීලකයන්',
    'admin.allfarmers': 'සියලු ගොවීන්',
    'admin.allbuyers': 'සියලු ගැනුම්කරුවන්',
    'admin.selectrecipient': 'ලබන්නාගේ වර්ගය තෝරන්න',
    'admin.sendingemail': 'ඊමේල් යවමින්...',
    'admin.sendingsms': 'SMS යවමින්...',
    'admin.emailsent': 'ඊමේල් සාර්ථකව යවන ලදී',
    'admin.smssent': 'SMS සාර්ථකව යවන ලදී',
    'admin.emailfailed': 'ඊමේල් යැවීම අසාර්ථකයි. කරුණාකර නැවත උත්සාහ කරන්න.',
    'admin.smsfailed': 'SMS යැවීම අසාර්ථකයි. කරුණාකර දුරකථන අංකය පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
    'admin.fillfields': 'කරුණාකර සියලු ක්ෂේත්‍ර පුරවන්න',
    'admin.enterphone': 'කරුණාකර දුරකථන අංකයක් ඇතුළත් කරන්න',
    'admin.enteremail': 'ඊමේල් ලිපිනය ඇතුළත් කරන්න',
    'admin.entersubject': 'ඊමේල් විෂය ඇතුළත් කරන්න',
    'admin.entermessage': 'ඔබගේ පණිවිඩය ඇතුළත් කරන්න',
    'admin.enterphonenumber': 'දුරකථන අංකය ඇතුළත් කරන්න',
    'admin.maxchars': 'අක්ෂර',
    'admin.refreshphone': 'දුරකථන අංක නැවුම් කරන්න',
    
    // Common
    'common.loading': 'පූරණය වෙමින්...',
    'common.error': 'යමක් වැරදුණි',
    'common.save': 'සුරකින්න',
    'common.cancel': 'අවලංගු කරන්න',
    'common.submit': 'ඉදිරිපත් කරන්න',
    'common.price': 'මිල',
    'common.quantity': 'ප්‍රමාණය',
    'common.contact': 'සම්බන්ධතාවය',
    'common.name': 'නම',
    'common.usertype': 'පරිශීලක වර්ගය',
    'common.location': 'ස්ථානය',
    'common.verified': 'සත්‍යාපිත',
    'common.unverified': 'සත්‍යාපිත නොවන',
    'common.notspecified': 'සඳහන් කර නැත',
    'common.nophone': 'දුරකථන අංක හමු නොවිණි',
    'common.loadingphone': 'දුරකථන අංක පූරණය වෙමින්...',
    'common.back': 'ආපසු',
    'common.next': 'ඊළඟ',
    'common.previous': 'පෙර',
    'common.search': 'සොයන්න',
    'common.filter': 'පෙරහන',
    'common.sort': 'වර්ග කරන්න',
    'common.date': 'දිනය',
    'common.time': 'කාලය',
    'common.status': 'තත්ත්වය',
    'common.actions': 'ක්‍රියාමාර්ග',
    
    // Authentication
    'auth.email': 'විද්‍යුත් තැපෑල',
    'auth.password': 'මුරපදය',
    'auth.login': 'ප්‍රවේශය',
    'auth.register': 'ලියාපදිංචිය',
    'auth.farmer': 'ගොවියා',
    'auth.buyer': 'ගැනුම්කරු',
    'auth.name': 'සම්පූර්ණ නම',
    'auth.phone': 'දුරකථන අංකය',
    'auth.location': 'ස්ථානය',
    'auth.logout': 'ඉවත් වන්න',
    'auth.profile': 'පැතිකඩ',
    'auth.settings': 'සැකසුම්',
    
    // Buttons and actions
    'btn.send': 'යවන්න',
    'btn.edit': 'සංස්කරණය',
    'btn.delete': 'මකන්න',
    'btn.view': 'බලන්න',
    'btn.update': 'යාවත්කාලීන කරන්න',
    'btn.create': 'සාදන්න',
    'btn.add': 'එක් කරන්න',
    'btn.remove': 'ඉවත් කරන්න',
    'btn.close': 'වසන්න',
    'btn.open': 'විවෘත කරන්න',
    'btn.refresh': 'නැවුම් කරන්න',
    'btn.reset': 'යළි පිහිටුවන්න',
    'btn.confirm': 'තහවුරු කරන්න',
  },
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.marketplace': 'சந்தை',
    'nav.blog': 'வலைப்பதிவு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.login': 'உள்நுழைய',
    'nav.register': 'பதிவு',
    'nav.dashboard': 'கட்டுப்பாட்டு பலகை',
    'nav.admin': 'நிர்வாகி',
    'nav.weather': 'வானிலை',
    'nav.aichat': 'AI அரட்டை',
    'nav.calendar': 'பயிர் நாட்காட்டி',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.cart': 'வண்டி',
    'nav.chat': 'அரட்டை',
    
    // Homepage
    'home.title': 'இலங்கை விவசாயிகளுடன் நேரடியாக இணைக்கவும்',
    'home.subtitle': 'புதிய விளைபொருட்கள், நியாயமான விலைகள், AI இயங்கும் நுண்ணறிவு',
    'home.cta.farmer': 'நான் ஒரு விவசாயி',
    'home.cta.buyer': 'நான் ஒரு வாங்குபவர்',
    'home.ai.title': 'AI சக்தி வாய்ந்த விவசாயம்',
    'home.ai.description': 'பயிர்கள், விலைகள் மற்றும் விவசாய நுட்பங்களுக்கான புத்திசாலித்தனமான பரிந்துரைகளைப் பெறுங்கள்',
    
    // Marketplace
    'marketplace.title': 'புதிய விளைபொருட்கள் சந்தை',
    'marketplace.search': 'தயாரிப்புகளைத் தேடு...',
    'marketplace.filter.all': 'அனைத்து வகைகள்',
    'marketplace.filter.vegetables': 'காய்கறிகள்',
    'marketplace.filter.fruits': 'பழங்கள்',
    'marketplace.filter.grains': 'தானியங்கள்',
    'marketplace.addtocart': 'வண்டியில் சேர்க்கவும்',
    'marketplace.viewproduct': 'தயாரிப்பைப் பார்க்கவும்',
    
    // Admin
    'admin.communications': 'தொடர்பு',
    'admin.sendemail': 'மின்னஞ்சல் அனுப்பு',
    'admin.sendsms': 'SMS அனுப்பு',
    'admin.phonenumbers': 'தொலைபேசி எண்கள்',
    'admin.recipient': 'பெறுபவர்',
    'admin.subject': 'பொருள்',
    'admin.message': 'செய்தி',
    'admin.customEmail': 'தனிப்பயன் மின்னஞ்சல்',
    'admin.customPhone': 'தனிப்பயன் தொலைபேசி எண்',
    'admin.allusers': 'அனைத்து பயனர்கள்',
    'admin.allfarmers': 'அனைத்து விவசாயிகள்',
    'admin.allbuyers': 'அனைத்து வாங்குபவர்கள்',
    'admin.selectrecipient': 'பெறுபவர் வகையைத் தேர்வு செய்யவும்',
    'admin.sendingemail': 'மின்னஞ்சல் அனுப்புகிறது...',
    'admin.sendingsms': 'SMS அனுப்புகிறது...',
    'admin.emailsent': 'மின்னஞ்சல் வெற்றிகரமாக அனுப்பப்பட்டது',
    'admin.smssent': 'SMS வெற்றிகரமாக அனுப்பப்பட்டது',
    'admin.emailfailed': 'மின்னஞ்சல் அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'admin.smsfailed': 'SMS அனுப்ப முடியவில்லை. தொலைபேசி எண்ணைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    'admin.fillfields': 'அனைத்து புலங்களையும் நிரப்பவும்',
    'admin.enterphone': 'தொலைபேசி எண்ணை உள்ளிடவும்',
    'admin.enteremail': 'மின்னஞ்சல் முகவரியை உள்ளிடவும்',
    'admin.entersubject': 'மின்னஞ்சல் பொருளை உள்ளிடவும்',
    'admin.entermessage': 'உங்கள் செய்தியை உள்ளிடவும்',
    'admin.enterphonenumber': 'தொலைபேசி எண்ணை உள்ளிடவும்',
    'admin.maxchars': 'எழுத்துக்கள்',
    'admin.refreshphone': 'தொலைபேசி எண்களை புதுப்பிக்கவும்',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'ஏதோ தவறு நடந்தது',
    'common.save': 'சேமி',
    'common.cancel': 'ரத்து செய்',
    'common.submit': 'சமர்ப்பி',
    'common.price': 'விலை',
    'common.quantity': 'அளவு',
    'common.contact': 'தொடர்பு',
    'common.name': 'பெயர்',
    'common.usertype': 'பயனர் வகை',
    'common.location': 'இடம்',
    'common.verified': 'சரிபார்க்கப்பட்டது',
    'common.unverified': 'சரிபார்க்கப்படவில்லை',
    'common.notspecified': 'குறிப்பிடப்படவில்லை',
    'common.nophone': 'தொலைபேசி எண்கள் எதுவும் இல்லை',
    'common.loadingphone': 'தொலைபேசி எண்களை ஏற்றுகிறது...',
    'common.back': 'திரும்பு',
    'common.next': 'அடுத்தது',
    'common.previous': 'முந்தைய',
    'common.search': 'தேடு',
    'common.filter': 'வடிகட்டி',
    'common.sort': 'வரிசைப்படுத்து',
    'common.date': 'தேதி',
    'common.time': 'நேரம்',
    'common.status': 'நிலை',
    'common.actions': 'செயல்கள்',
    
    // Authentication
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.login': 'உள்நுழைய',
    'auth.register': 'பதிவு செய்ய',
    'auth.farmer': 'விவசாயி',
    'auth.buyer': 'வாங்குபவர்',
    'auth.name': 'முழு பெயர்',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.location': 'இடம்',
    'auth.logout': 'வெளியேறு',
    'auth.profile': 'சுயவிவரம்',
    'auth.settings': 'அமைப்புகள்',
    
    // Buttons and actions
    'btn.send': 'அனுப்பு',
    'btn.edit': 'திருத்து',
    'btn.delete': 'நீக்கு',
    'btn.view': 'பார்',
    'btn.update': 'புதுப்பி',
    'btn.create': 'உருவாக்கு',
    'btn.add': 'சேர்',
    'btn.remove': 'நீக்கு',
    'btn.close': 'மூடு',
    'btn.open': 'திற',
    'btn.refresh': 'புதுப்பி',
    'btn.reset': 'மீட்டமை',
    'btn.confirm': 'உறுதிப்படுத்து',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};