import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.marketplace': 'Marketplace',
    'nav.blog': 'Blog',
    'nav.about': 'About',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.weather': 'Weather',
    'nav.aichat': 'AI Chat',
    'nav.calendar': 'Crop Calendar',
    'nav.notifications': 'Notifications',
    'nav.cart': 'Cart',
    'nav.chat': 'Chat',
    
    // Homepage
    'home.title': 'Connect Directly with Sri Lankan Farmers',
    'home.subtitle': 'Fresh produce, fair prices, AI-powered insights',
    'home.cta.farmer': 'I am a Farmer',
    'home.cta.buyer': 'I am a Buyer',
    'home.ai.title': 'AI-Powered Agriculture',
    'home.ai.description': 'Get smart recommendations for crops, prices, and farming techniques',
    
    // Marketplace
    'marketplace.title': 'Fresh Produce Marketplace',
    'marketplace.search': 'Search products...',
    'marketplace.filter.all': 'All Categories',
    'marketplace.filter.vegetables': 'Vegetables',
    'marketplace.filter.fruits': 'Fruits',
    'marketplace.filter.grains': 'Grains',
    'marketplace.addtocart': 'Add to Cart',
    'marketplace.viewproduct': 'View Product',
    
    // Admin
    'admin.communications': 'Communications',
    'admin.sendemail': 'Send Email',
    'admin.sendsms': 'Send SMS',
    'admin.phonenumbers': 'Phone Numbers',
    'admin.recipient': 'Recipient',
    'admin.subject': 'Subject',
    'admin.message': 'Message',
    'admin.customEmail': 'Custom Email',
    'admin.customPhone': 'Custom Phone Number',
    'admin.allusers': 'All Users',
    'admin.allfarmers': 'All Farmers',
    'admin.allbuyers': 'All Buyers',
    'admin.selectrecipient': 'Select recipient type',
    'admin.sendingemail': 'Sending Email...',
    'admin.sendingsms': 'Sending SMS...',
    'admin.emailsent': 'Email Sent Successfully',
    'admin.smssent': 'SMS Sent Successfully',
    'admin.emailfailed': 'Failed to send email. Please try again.',
    'admin.smsfailed': 'Failed to send SMS. Please check the phone number and try again.',
    'admin.fillfields': 'Please fill in all fields',
    'admin.enterphone': 'Please enter a phone number',
    'admin.enteremail': 'Enter email address',
    'admin.entersubject': 'Enter email subject',
    'admin.entermessage': 'Enter your message',
    'admin.enterphonenumber': 'Enter phone number',
    'admin.maxchars': 'characters',
    'admin.refreshphone': 'Refresh Phone Numbers',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.contact': 'Contact',
    'common.name': 'Name',
    'common.usertype': 'User Type',
    'common.location': 'Location',
    'common.verified': 'Verified',
    'common.unverified': 'Unverified',
    'common.notspecified': 'Not specified',
    'common.nophone': 'No phone numbers found',
    'common.loadingphone': 'Loading phone numbers...',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.actions': 'Actions',
    
    // Authentication
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.farmer': 'Farmer',
    'auth.buyer': 'Buyer',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.location': 'Location',
    'auth.logout': 'Logout',
    'auth.profile': 'Profile',
    'auth.settings': 'Settings',
    
    // About page & Features
    'about.mission': 'Our Mission',
    'about.title': 'Transforming Sri Lankan Agriculture',
    'about.subtitle': "We're building a direct connection between farmers and buyers, powered by AI and designed for the Sri Lankan agricultural community.",
    'about.empowering': 'Empowering Sri Lankan Farmers Through Technology',
    'about.description1': 'AgroLink Sri Lanka was born from a simple observation: too many hardworking farmers struggle to get fair prices for their produce due to complex supply chains and lack of direct market access.',
    'about.description2': 'Our platform eliminates middlemen, provides AI-powered farming insights, and creates a transparent marketplace where farmers can thrive and buyers can access fresh, quality produce directly from the source.',
    'about.features.fairpricing': 'Fair pricing for farmers',
    'about.features.freshproduce': 'Fresh produce for consumers',
    'about.features.sustainable': 'Sustainable agriculture practices',
    'features.ai.title': 'AI-Powered Insights',
    'features.ai.description': 'Get intelligent crop recommendations, price predictions, and farming advice',
    'features.connection.title': 'Direct Connection',
    'features.connection.description': 'Connect farmers and buyers without middlemen for fair pricing',
    'features.market.title': 'Market Intelligence',
    'features.market.description': 'Real-time market prices and demand forecasting',
    'features.multilingual.title': 'Multilingual Support',
    'features.multilingual.description': 'Available in English, Sinhala, and Tamil languages',
    
    // Home page content
    'home.cta.title': 'Ready to Transform Sri Lankan Agriculture?',
    'home.cta.description': 'Join thousands of farmers and buyers already using our AI-powered platform',
    'home.blog.title': 'Stay Updated with Farming News',
    'home.blog.description': 'Discover the latest trends, tips, and insights from the agricultural world',
    'home.stats.farmers': 'Active Farmers',
    'home.stats.buyers': 'Verified Buyers',
    'home.stats.varieties': 'Crop Varieties',
    'home.stats.support': 'AI Support',
    
    // Blog & Articles
    'blog.featured': 'Featured Article',
    'blog.search': 'Search articles...',
    'blog.readmore': 'Read More',
    'blog.readfull': 'Read Full Article',
    'blog.viewall': 'View All Articles',
    'blog.subtitle': 'Stay updated with the latest farming tips, market insights, and agricultural innovations',
    'blog.category.all': 'All Categories',
    'blog.category.ai': 'AI & Technology',
    'blog.category.sustainability': 'Sustainability',
    'blog.category.market': 'Market Analysis',
    'blog.category.water': 'Water Management',
    'blog.category.climate': 'Climate Adaptation',
    'blog.category.health': 'Health & Safety',
    'blog.noresults': 'No articles found',
    'blog.noresults.description': 'Try adjusting your search terms or filters',
    'blog.stayupdated': 'Stay Updated',
    'blog.newsletter': 'Subscribe to our newsletter for the latest farming tips and market insights',
    'blog.insights': 'Latest Agricultural Insights',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'unread notifications',
    'notifications.allcaught': 'All caught up!',
    'notifications.markallread': 'Mark All as Read',
    'notifications.nonefound': 'No notifications yet',
    'notifications.new': 'New',
    'notifications.urgent': 'Urgent',
    'notifications.markedread': 'Marked as read',
    'notifications.markedread.desc': 'Notification has been marked as read.',
    'notifications.deleted': 'Notification deleted',
    'notifications.deleted.desc': 'Notification has been removed.',
    'notifications.allread': 'All notifications marked as read',
    'notifications.allread.desc': 'All notifications have been marked as read.',
    
    // CTA Buttons
    'cta.explore': 'Explore Marketplace',
    'cta.tryai': 'Try AI Assistant',
    'cta.readarticle': 'Read Article',
    
    // Buttons and actions
    'btn.send': 'Send',
    'btn.edit': 'Edit',
    'btn.delete': 'Delete',
    'btn.view': 'View',
    'btn.update': 'Update',
    'btn.create': 'Create',
    'btn.add': 'Add',
    'btn.remove': 'Remove',
    'btn.close': 'Close',
    'btn.open': 'Open',
    'btn.refresh': 'Refresh',
    'btn.reset': 'Reset',
    'btn.confirm': 'Confirm',
  },
  si: {
    // Navigation
    'nav.home': 'මුල් පිටුව',
    'nav.marketplace': 'වෙළඳපල',
    'nav.blog': 'බ්ලොග්',
    'nav.about': 'අපි ගැන',
    'nav.login': 'ප්‍රවේශය',
    'nav.register': 'ලියාපදිංචිය',
    'nav.dashboard': 'උපකරණ පුවරුව',
    'nav.admin': 'පරිපාලක',
    'nav.weather': 'කාලගුණය',
    'nav.aichat': 'AI කතාබස්',
    'nav.calendar': 'බෝග දිනදර්ශනය',
    'nav.notifications': 'දැනුම්දීම්',
    'nav.cart': 'කරත්තය',
    'nav.chat': 'කතාබස්',
    
    // Homepage
    'home.title': 'ශ්‍රී ලංකාවේ ගොවීන් සමඟ සෘජුවම සම්බන්ධ වන්න',
    'home.subtitle': 'නැවුම් නිෂ්පාදන, සාධාරණ මිල, AI බුද්ධිමත් අවබෝධය',
    'home.cta.farmer': 'මම ගොවියෙක්',
    'home.cta.buyer': 'මම ගැනුම්කරුවෙක්',
    'home.ai.title': 'AI බලගන්වන කෘෂිකර්මාන්තය',
    'home.ai.description': 'බෝග, මිල සහ ගොවිතාන් ක්‍රම සඳහා බුද්ධිමත් නිර්දේශ ලබා ගන්න',
    
    // Marketplace
    'marketplace.title': 'නැවුම් නිෂ්පාදන වෙළඳපල',
    'marketplace.search': 'නිෂ්පාදන සොයන්න...',
    'marketplace.filter.all': 'සියලු කාණ්ඩ',
    'marketplace.filter.vegetables': 'එළවළු',
    'marketplace.filter.fruits': 'පලතුරු',
    'marketplace.filter.grains': 'ධාන්‍ය',
    'marketplace.addtocart': 'කරත්තයට එක් කරන්න',
    'marketplace.viewproduct': 'නිෂ්පාදනය බලන්න',
    
    // Admin
    'admin.communications': 'සන්නිවේදනය',
    'admin.sendemail': 'ඊමේල් යවන්න',
    'admin.sendsms': 'SMS යවන්න',
    'admin.phonenumbers': 'දුරකථන අංක',
    'admin.recipient': 'ලබන්නා',
    'admin.subject': 'විෂය',
    'admin.message': 'පණිවිඩය',
    'admin.customEmail': 'අභිරුචි ඊමේල්',
    'admin.customPhone': 'අභිරුචි දුරකථන අංකය',
    'admin.allusers': 'සියලු පරිශීලකයන්',
    'admin.allfarmers': 'සියලු ගොවීන්',
    'admin.allbuyers': 'සියලු ගැනුම්කරුවන්',
    'admin.selectrecipient': 'ලබන්නාගේ වර්ගය තෝරන්න',
    'admin.sendingemail': 'ඊමේල් යවමින්...',
    'admin.sendingsms': 'SMS යවමින්...',
    'admin.emailsent': 'ඊමේල් සාර්ථකව යවන ලදී',
    'admin.smssent': 'SMS සාර්ථකව යවන ලදී',
    'admin.emailfailed': 'ඊමේල් යැවීම අසාර්ථකයි. කරුණාකර නැවත උත්සාහ කරන්න.',
    'admin.smsfailed': 'SMS යැවීම අසාර්ථකයි. කරුණාකර දුරකථන අංකය පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
    'admin.fillfields': 'කරුණාකර සියලු ක්ෂේත්‍ර පුරවන්න',
    'admin.enterphone': 'කරුණාකර දුරකථන අංකයක් ඇතුළත් කරන්න',
    'admin.enteremail': 'ඊමේල් ලිපිනය ඇතුළත් කරන්න',
    'admin.entersubject': 'ඊමේල් විෂය ඇතුළත් කරන්න',
    'admin.entermessage': 'ඔබගේ පණිවිඩය ඇතුළත් කරන්න',
    'admin.enterphonenumber': 'දුරකථන අංකය ඇතුළත් කරන්න',
    'admin.maxchars': 'අක්ෂර',
    'admin.refreshphone': 'දුරකථන අංක නැවුම් කරන්න',
    
    // Common
    'common.loading': 'පූරණය වෙමින්...',
    'common.error': 'යමක් වැරදුණි',
    'common.save': 'සුරකින්න',
    'common.cancel': 'අවලංගු කරන්න',
    'common.submit': 'ඉදිරිපත් කරන්න',
    'common.price': 'මිල',
    'common.quantity': 'ප්‍රමාණය',
    'common.contact': 'සම්බන්ධතාවය',
    'common.name': 'නම',
    'common.usertype': 'පරිශීලක වර්ගය',
    'common.location': 'ස්ථානය',
    'common.verified': 'සත්‍යාපිත',
    'common.unverified': 'සත්‍යාපිත නොවන',
    'common.notspecified': 'සඳහන් කර නැත',
    'common.nophone': 'දුරකථන අංක හමු නොවිණි',
    'common.loadingphone': 'දුරකථන අංක පූරණය වෙමින්...',
    'common.back': 'ආපසු',
    'common.next': 'ඊළඟ',
    'common.previous': 'පෙර',
    'common.search': 'සොයන්න',
    'common.filter': 'පෙරහන',
    'common.sort': 'වර්ග කරන්න',
    'common.date': 'දිනය',
    'common.time': 'කාලය',
    'common.status': 'තත්ත්වය',
    'common.actions': 'ක්‍රියාමාර්ග',
    
    // Authentication
    'auth.email': 'විද්‍යුත් තැපෑල',
    'auth.password': 'මුරපදය',
    'auth.login': 'ප්‍රවේශය',
    'auth.register': 'ලියාපදිංචිය',
    'auth.farmer': 'ගොවියා',
    'auth.buyer': 'ගැනුම්කරු',
    'auth.name': 'සම්පූර්ණ නම',
    'auth.phone': 'දුරකථන අංකය',
    'auth.location': 'ස්ථානය',
    'auth.logout': 'ඉවත් වන්න',
    'auth.profile': 'පැතිකඩ',
    'auth.settings': 'සැකසුම්',
    
    // About page & Features
    'about.mission': 'අපගේ මෙහෙවර',
    'about.title': 'ශ්‍රී ලංකාවේ කෘෂිකර්මාන්තය පරිවර්තනය කිරීම',
    'about.subtitle': 'අපි AI තාක්ෂණයෙන් බලගන්වන ලද සහ ශ්‍රී ලංකාවේ කෘෂිකාර්මික ප්‍රජාව සඳහා නිර්මාණය කරන ලද ගොවීන් සහ ගැනුම්කරුවන් අතර සෘජු සම්බන්ධතාවයක් ගොඩනගමින් සිටිමු.',
    'about.empowering': 'තාක්ෂණය හරහා ශ්‍රී ලංකාවේ ගොවීන් බලගන්වනවා',
    'about.description1': 'AgroLink ශ්‍රී ලංකාව උපත ලැබුවේ සරල නිරීක්ෂණයකින්: බොහෝ වෙහෙස මහන්සි වී වැඩ කරන ගොවීන් සංකීර්ණ සැපයුම් දාම සහ සෘජු වෙළඳපල ප්‍රවේශයේ අඩුව හේතුවෙන් ඔවුන්ගේ නිෂ්පාදන සඳහා සාධාරණ මිල ලබා ගැනීමට අරගල කරති.',
    'about.description2': 'අපගේ වේදිකාව අතරමැදියන් ඉවත් කරයි, AI බලගන්වන ගොවිතැන් අවබෝධය සපයයි, සහ ගොවීන්ට සමෘද්ධිමත් විය හැකි සහ ගැනුම්කරුවන්ට සෘජුවම මූලාශ්‍රයෙන් නැවුම්, ගුණාත්මක නිෂ්පාදනවලට ප්‍රවේශ විය හැකි විනිවිද පෙනෙන වෙළඳපළක් නිර්මාණය කරයි.',
    'about.features.fairpricing': 'ගොවීන්ට සාධාරණ මිල ගණන්',
    'about.features.freshproduce': 'පාරිභෝගිකයන්ට නැවුම් නිෂ්පාදන',
    'about.features.sustainable': 'තිරසාර කෘෂිකාර්මික ක්‍රම',
    'features.ai.title': 'AI බලගන්වන අවබෝධය',
    'features.ai.description': 'බුද්ධිමත් බෝග නිර්දේශ, මිල අනාවැකි සහ ගොවිතැන් උපදෙස් ලබා ගන්න',
    'features.connection.title': 'සෘජු සම්බන්ධතාවය',
    'features.connection.description': 'සාධාරණ මිල ගණන් සඳහා අතරමැදියන් නොමැතිව ගොවීන් සහ ගැනුම්කරුවන් සම්බන්ධ කරන්න',
    'features.market.title': 'වෙළඳපල බුද්ධිය',
    'features.market.description': 'තත්‍ය කාලීන වෙළඳපල මිල සහ ඉල්ලුම් පුරෝකථනය',
    'features.multilingual.title': 'බහුභාෂික සහාය',
    'features.multilingual.description': 'ඉංග්‍රීසි, සිංහල සහ දමිළ භාෂාවලින් ලබා ගත හැකිය',
    
    // Home page content
    'home.cta.title': 'ශ්‍රී ලංකාවේ කෘෂිකර්මාන්තය පරිවර්තනය කිරීමට සූදානම්ද?',
    'home.cta.description': 'දැනටමත් අපගේ AI බලගන්වන වේදිකාව භාවිතා කරන ගොවීන් සහ ගැනුම්කරුවන් දහස් ගණනකට එක්වන්න',
    'home.blog.title': 'ගොවිතැන් පුවත් සමඟ යාවත්කාලීන කරන්න',
    'home.blog.description': 'කෘෂිකාර්මික ලෝකයේ නවතම ප්‍රවණතා, ඉඟි සහ අවබෝධයන් සොයා ගන්න',
    'home.stats.farmers': 'සක්‍රීය ගොවීන්',
    'home.stats.buyers': 'සත්‍යාපිත ගැනුම්කරුවන්',
    'home.stats.varieties': 'බෝග වර්ග',
    'home.stats.support': 'AI සහාය',
    
    // Blog & Articles
    'blog.featured': 'විශේෂ ලේඛනය',
    'blog.search': 'ලේඛන සොයන්න...',
    'blog.readmore': 'තව කියවන්න',
    'blog.readfull': 'සම්පූර්ණ ලේඛනය කියවන්න',
    'blog.viewall': 'සියලු ලේඛන බලන්න',
    'blog.subtitle': 'නවතම ගොවිතැන් ඉඟි, වෙළඳපල අවබෝධයන් සහ කෘෂිකාර්මික නවෝත්පාදන සමඟ යාවත්කාලීන කරන්න',
    'blog.category.all': 'සියලු කාණ්ඩ',
    'blog.category.ai': 'AI සහ තාක්ෂණය',
    'blog.category.sustainability': 'තිරසාරත්වය',
    'blog.category.market': 'වෙළඳපල විශ්ලේෂණය',
    'blog.category.water': 'ජල කළමනාකරණය',
    'blog.category.climate': 'දේශගුණ අනුවර්තනය',
    'blog.category.health': 'සෞඛ්‍ය සහ ආරක්ෂාව',
    'blog.noresults': 'ලේඛන හමු නොවිණි',
    'blog.noresults.description': 'ඔබගේ සෙවුම් පද හෝ පෙරහන් සකස් කිරීමට උත්සාහ කරන්න',
    'blog.stayupdated': 'යාවත්කාලීන රහසින්',
    'blog.newsletter': 'නවතම ගොවිතැන් ඉඟි සහ වෙළඳපල අවබෝධයන් සඳහා අපගේ පුවත්පතට දායක වන්න',
    'blog.insights': 'නවතම කෘෂිකාර්මික අවබෝධයන්',
    
    // Notifications
    'notifications.title': 'දැනුම්දීම්',
    'notifications.unread': 'නොකියවූ දැනුම්දීම්',
    'notifications.allcaught': 'සියල්ල සම්පූර්ණයි!',
    'notifications.markallread': 'සියල්ල කියවූ ලෙස සලකුණු කරන්න',
    'notifications.nonefound': 'තවම දැනුම්දීම් නැත',
    'notifications.new': 'නව',
    'notifications.urgent': 'හදිසි',
    'notifications.markedread': 'කියවූ ලෙස සලකුණු කරන ලදී',
    'notifications.markedread.desc': 'දැනුම්දීම කියවූ ලෙස සලකුණු කර ඇත.',
    'notifications.deleted': 'දැනුම්දීම මකන ලදී',
    'notifications.deleted.desc': 'දැනුම්දීම ඉවත් කර ඇත.',
    'notifications.allread': 'සියලු දැනුම්දීම් කියවූ ලෙස සලකුණු කරන ලදී',
    'notifications.allread.desc': 'සියලු දැනුම්දීම් කියවූ ලෙස සලකුණු කර ඇත.',
    
    // CTA Buttons
    'cta.explore': 'වෙළඳපල ගවේෂණය කරන්න',
    'cta.tryai': 'AI සහායක අත්හදා බලන්න',
    'cta.readarticle': 'ලේඛනය කියවන්න',
    
    // Buttons and actions
    'btn.send': 'යවන්න',
    'btn.edit': 'සංස්කරණය',
    'btn.delete': 'මකන්න',
    'btn.view': 'බලන්න',
    'btn.update': 'යාවත්කාලීන කරන්න',
    'btn.create': 'සාදන්න',
    'btn.add': 'එක් කරන්න',
    'btn.remove': 'ඉවත් කරන්න',
    'btn.close': 'වසන්න',
    'btn.open': 'විවෘත කරන්න',
    'btn.refresh': 'නැවුම් කරන්න',
    'btn.reset': 'යළි පිහිටුවන්න',
    'btn.confirm': 'තහවුරු කරන්න',
  },
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.marketplace': 'சந்தை',
    'nav.blog': 'வலைப்பதிவு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.login': 'உள்நுழைய',
    'nav.register': 'பதிவு',
    'nav.dashboard': 'கட்டுப்பாட்டு பலகை',
    'nav.admin': 'நிர்வாகி',
    'nav.weather': 'வானிலை',
    'nav.aichat': 'AI அரட்டை',
    'nav.calendar': 'பயிர் நாட்காட்டி',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.cart': 'வண்டி',
    'nav.chat': 'அரட்டை',
    
    // Homepage
    'home.title': 'இலங்கை விவசாயிகளுடன் நேரடியாக இணைக்கவும்',
    'home.subtitle': 'புதிய விளைபொருட்கள், நியாயமான விலைகள், AI இயங்கும் நுண்ணறிவு',
    'home.cta.farmer': 'நான் ஒரு விவசாயி',
    'home.cta.buyer': 'நான் ஒரு வாங்குபவர்',
    'home.ai.title': 'AI சக்தி வாய்ந்த விவசாயம்',
    'home.ai.description': 'பயிர்கள், விலைகள் மற்றும் விவசாய நுட்பங்களுக்கான புத்திசாலித்தனமான பரிந்துரைகளைப் பெறுங்கள்',
    
    // Marketplace
    'marketplace.title': 'புதிய விளைபொருட்கள் சந்தை',
    'marketplace.search': 'தயாரிப்புகளைத் தேடு...',
    'marketplace.filter.all': 'அனைத்து வகைகள்',
    'marketplace.filter.vegetables': 'காய்கறிகள்',
    'marketplace.filter.fruits': 'பழங்கள்',
    'marketplace.filter.grains': 'தானியங்கள்',
    'marketplace.addtocart': 'வண்டியில் சேர்க்கவும்',
    'marketplace.viewproduct': 'தயாரிப்பைப் பார்க்கவும்',
    
    // Admin
    'admin.communications': 'தொடர்பு',
    'admin.sendemail': 'மின்னஞ்சல் அனுப்பு',
    'admin.sendsms': 'SMS அனுப்பு',
    'admin.phonenumbers': 'தொலைபேசி எண்கள்',
    'admin.recipient': 'பெறுபவர்',
    'admin.subject': 'பொருள்',
    'admin.message': 'செய்தி',
    'admin.customEmail': 'தனிப்பயன் மின்னஞ்சல்',
    'admin.customPhone': 'தனிப்பயன் தொலைபேசி எண்',
    'admin.allusers': 'அனைத்து பயனர்கள்',
    'admin.allfarmers': 'அனைத்து விவசாயிகள்',
    'admin.allbuyers': 'அனைத்து வாங்குபவர்கள்',
    'admin.selectrecipient': 'பெறுபவர் வகையைத் தேர்வு செய்யவும்',
    'admin.sendingemail': 'மின்னஞ்சல் அனுப்புகிறது...',
    'admin.sendingsms': 'SMS அனுப்புகிறது...',
    'admin.emailsent': 'மின்னஞ்சல் வெற்றிகரமாக அனுப்பப்பட்டது',
    'admin.smssent': 'SMS வெற்றிகரமாக அனுப்பப்பட்டது',
    'admin.emailfailed': 'மின்னஞ்சல் அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'admin.smsfailed': 'SMS அனுப்ப முடியவில்லை. தொலைபேசி எண்ணைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    'admin.fillfields': 'அனைத்து புலங்களையும் நிரப்பவும்',
    'admin.enterphone': 'தொலைபேசி எண்ணை உள்ளிடவும்',
    'admin.enteremail': 'மின்னஞ்சல் முகவரியை உள்ளிடவும்',
    'admin.entersubject': 'மின்னஞ்சல் பொருளை உள்ளிடவும்',
    'admin.entermessage': 'உங்கள் செய்தியை உள்ளிடவும்',
    'admin.enterphonenumber': 'தொலைபேசி எண்ணை உள்ளிடவும்',
    'admin.maxchars': 'எழுத்துக்கள்',
    'admin.refreshphone': 'தொலைபேசி எண்களை புதுப்பிக்கவும்',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'ஏதோ தவறு நடந்தது',
    'common.save': 'சேமி',
    'common.cancel': 'ரத்து செய்',
    'common.submit': 'சமர்ப்பி',
    'common.price': 'விலை',
    'common.quantity': 'அளவு',
    'common.contact': 'தொடர்பு',
    'common.name': 'பெயர்',
    'common.usertype': 'பயனர் வகை',
    'common.location': 'இடம்',
    'common.verified': 'சரிபார்க்கப்பட்டது',
    'common.unverified': 'சரிபார்க்கப்படவில்லை',
    'common.notspecified': 'குறிப்பிடப்படவில்லை',
    'common.nophone': 'தொலைபேசி எண்கள் எதுவும் இல்லை',
    'common.loadingphone': 'தொலைபேசி எண்களை ஏற்றுகிறது...',
    'common.back': 'திரும்பு',
    'common.next': 'அடுத்தது',
    'common.previous': 'முந்தைய',
    'common.search': 'தேடு',
    'common.filter': 'வடிகட்டி',
    'common.sort': 'வரிசைப்படுத்து',
    'common.date': 'தேதி',
    'common.time': 'நேரம்',
    'common.status': 'நிலை',
    'common.actions': 'செயல்கள்',
    
    // Authentication
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.login': 'உள்நுழைய',
    'auth.register': 'பதிவு செய்ய',
    'auth.farmer': 'விவசாயி',
    'auth.buyer': 'வாங்குபவர்',
    'auth.name': 'முழு பெயர்',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.location': 'இடம்',
    'auth.logout': 'வெளியேறு',
    'auth.profile': 'சுயவிவரம்',
    'auth.settings': 'அமைப்புகள்',
    
    // About page & Features
    'about.mission': 'எங்கள் பணி',
    'about.title': 'இலங்கை விவசாயத்தை மாற்றுதல்',
    'about.subtitle': 'நாங்கள் AI ஆல் இயக்கப்படும் மற்றும் இலங்கை விவசாய சமூகத்திற்காக வடிவமைக்கப்பட்ட விவசாயிகள் மற்றும் வாங்குபவர்களுக்கு இடையே நேரடி தொடர்பை உருவாக்கி வருகிறோம்.',
    'about.empowering': 'தொழில்நுட்பத்தின் மூலம் இலங்கை விவசாயிகளை வலுப்படுத்துதல்',
    'about.description1': 'AgroLink இலங்கை ஒரு எளிய கவனிப்பிலிருந்து பிறந்தது: பல கடின உழைப்பாளி விவசாயிகள் சிக்கலான வழங்கல் சங்கிலிகள் மற்றும் நேரடி சந்தை அணுகல் இல்லாததால் தங்கள் விளைபொருட்களுக்கு நியாயமான விலை பெற போராடுகின்றனர்.',
    'about.description2': 'எங்கள் மேடை இடைத்தரகர்களை நீக்குகிறது, AI சார்ந்த விவசாய நுண்ணறிவுகளை வழங்குகிறது, மற்றும் விவசாயிகள் செழிக்கக்கூடிய மற்றும் வாங்குபவர்கள் மூலத்திலிருந்து நேரடியாக புதிய, தரமான விளைபொருட்களை அணுகக்கூடிய வெளிப்படையான சந்தையை உருவாக்குகிறது.',
    'about.features.fairpricing': 'விவசாயிகளுக்கு நியாயமான விலை',
    'about.features.freshproduce': 'நுகர்வோருக்கு புதிய விளைபொருட்கள்',
    'about.features.sustainable': 'நிலையான விவசாய நடைமுறைகள்',
    'features.ai.title': 'AI சார்ந்த நுண்ணறிவுகள்',
    'features.ai.description': 'புத்திசாலித்தனமான பயிர் பரிந்துரைகள், விலை கணிப்புகள் மற்றும் விவசாய ஆலோசனைகளைப் பெறுங்கள்',
    'features.connection.title': 'நேரடி இணைப்பு',
    'features.connection.description': 'நியாயமான விலையிடலுக்காக இடைத்தரகர்கள் இல்லாமல் விவசாயிகள் மற்றும் வாங்குபவர்களை இணைக்கவும்',
    'features.market.title': 'சந்தை நுண்ணறிவு',
    'features.market.description': 'நிகழ்நேர சந்தை விலைகள் மற்றும் தேவை முன்னறிவிப்பு',
    'features.multilingual.title': 'பன்மொழி ஆதரவு',
    'features.multilingual.description': 'ஆங்கிலம், சிங்களம் மற்றும் தமிழ் மொழிகளில் கிடைக்கிறது',
    
    // Home page content
    'home.cta.title': 'இலங்கை விவசாயத்தை மாற்ற தயாரா?',
    'home.cta.description': 'ஏற்கனவே எங்கள் AI சார்ந்த மேடையைப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகள் மற்றும் வாங்குபவர்களுடன் சேரவும்',
    'home.blog.title': 'விவசாய செய்திகளுடன் புதுப்பித்துக் கொள்ளுங்கள்',
    'home.blog.description': 'விவசாய உலகின் சமீபத்திய போக்குகள், குறிப்புகள் மற்றும் நுண்ணறிவுகளைக் கண்டறியுங்கள்',
    'home.stats.farmers': 'செயலில் உள்ள விவசாயிகள்',
    'home.stats.buyers': 'சரிபார்க்கப்பட்ட வாங்குபவர்கள்',
    'home.stats.varieties': 'பயிர் வகைகள்',
    'home.stats.support': 'AI ஆதரவு',
    
    // Blog & Articles
    'blog.featured': 'சிறப்பு கட்டுரை',
    'blog.search': 'கட்டுரைகளைத் தேடுங்கள்...',
    'blog.readmore': 'மேலும் படிக்கவும்',
    'blog.readfull': 'முழு கட்டுரையைப் படிக்கவும்',
    'blog.viewall': 'அனைத்து கட்டுரைகளையும் பார்க்கவும்',
    'blog.subtitle': 'சமீபத்திய விவசாய குறிப்புகள், சந்தை நுண்ணறிவுகள் மற்றும் விவசாய கண்டுபிடிப்புகளுடன் புதுப்பித்துக் கொள்ளுங்கள்',
    'blog.category.all': 'அனைத்து வகைகள்',
    'blog.category.ai': 'AI மற்றும் தொழில்நுட்பம்',
    'blog.category.sustainability': 'நிலைத்தன்மை',
    'blog.category.market': 'சந்தை பகுப்பாய்வு',
    'blog.category.water': 'நீர் மேலாண்மை',
    'blog.category.climate': 'காலநிலை தழுவல்',
    'blog.category.health': 'உடல்நலம் மற்றும் பாதுகாப்பு',
    'blog.noresults': 'எந்த கட்டுரையும் இல்லை',
    'blog.noresults.description': 'உங்கள் தேடல் சொற்கள் அல்லது வடிகட்டிகளை சரிசெய்ய முயற்சிக்கவும்',
    'blog.stayupdated': 'புதுப்பித்துக் கொள்ளுங்கள்',
    'blog.newsletter': 'சமீபத்திய விவசாய குறிப்புகள் மற்றும் சந்தை நுண்ணறிவுகளுக்கு எங்கள் செய்திமடலுக்கு குழுசேரவும்',
    'blog.insights': 'சமீபத்திய விவசாய நுண்ணறிவுகள்',
    
    // Notifications
    'notifications.title': 'அறிவிப்புகள்',
    'notifications.unread': 'படிக்கப்படாத அறிவிப்புகள்',
    'notifications.allcaught': 'அனைத்தும் முடிந்தது!',
    'notifications.markallread': 'எல்லாவற்றையும் படித்ததாகக் குறிக்கவும்',
    'notifications.nonefound': 'இன்னும் அறிவிப்புகள் இல்லை',
    'notifications.new': 'புதிய',
    'notifications.urgent': 'அவசரம்',
    'notifications.markedread': 'படித்ததாகக் குறிக்கப்பட்டது',
    'notifications.markedread.desc': 'அறிவிப்பு படித்ததாகக் குறிக்கப்பட்டுள்ளது.',
    'notifications.deleted': 'அறிவிப்பு நீக்கப்பட்டது',
    'notifications.deleted.desc': 'அறிவிப்பு அகற்றப்பட்டுள்ளது.',
    'notifications.allread': 'அனைத்து அறிவிப்புகளும் படித்ததாகக் குறிக்கப்பட்டன',
    'notifications.allread.desc': 'அனைத்து அறிவிப்புகளும் படித்ததாகக் குறிக்கப்பட்டுள்ளன.',
    
    // CTA Buttons
    'cta.explore': 'சந்தையை ஆராயுங்கள்',
    'cta.tryai': 'AI உதவியாளரை முயற்சிக்கவும்',
    'cta.readarticle': 'கட்டுரையைப் படிக்கவும்',
    
    // Buttons and actions
    'btn.send': 'அனுப்பு',
    'btn.edit': 'திருத்து',
    'btn.delete': 'நீக்கு',
    'btn.view': 'பார்',
    'btn.update': 'புதுப்பி',
    'btn.create': 'உருவாக்கு',
    'btn.add': 'சேர்',
    'btn.remove': 'நீக்கு',
    'btn.close': 'மூடு',
    'btn.open': 'திற',
    'btn.refresh': 'புதுப்பி',
    'btn.reset': 'மீட்டமை',
    'btn.confirm': 'உறுதிப்படுத்து',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};